site_name: Portafolio Ibero Puebla

theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-night
        name: Modo oscuro
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: Modo claro

  features:
    - navigation.indexes

nav:
  - Inicio: index.md
  - Sistemas Embebidos I:
      - "Tareas/index.md"
      - "Tareas/tarea1.md"
      - "Tareas/tarea2.md"
      - "Tareas/tarea3.md"
      - "Tareas/tarea4.md"
      - "Tareas/tarea5.md"
      - "Tareas/tarea6.md"
      - "Tareas/tarea7.md"
      - "Tareas/tarea8.md"
      - "Tareas/tarea9.md"
      - "Tareas/Examen.md"
      - "Tareas/ProyectoFinal.md"
  - Sistemas Embebidos II:
      - Tarea 1: "Sistemas Embebidos II/tarea1.md"
      - Tarea 2: "Sistemas Embebidos II/tarea2.md"
      - Tarea 3: "Sistemas Embebidos II/tarea3.md"

  - Proyecto de ingenier√≠a IV:
      - Semana 1: "proyecto-ingenieria-iv/semana-1.md"
      - Semana 3: "proyecto-ingenieria-iv/semana-3.md"
      - Semana 4: "proyecto-ingenieria-iv/semana-4.md"
      - Semana 5: "proyecto-ingenieria-iv/semana-5.md"
      - Semana 6: "proyecto-ingenieria-iv/semana-6.md"
      - Semana 7: "proyecto-ingenieria-iv/semana-7.md"
      - Semana 8: "proyecto-ingenieria-iv/semana-8.md"
      - Trello: "proyecto-ingenieria-iv/trello.md"
      - Proyecto Final: "proyecto-ingenieria-iv/ProyectoFinal.md"

markdown_extensions:
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
